steps:
  # Build the container image
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - --destination=gcr.io/$PROJECT_ID/image
      - --cache=true
      - --cache-ttl=168h
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "farmhand",
        "--image",
        "gcr.io/crypto-gohan/farmhand",
        "--region",
        "europe-west-1",
        "--platform",
        "managed",
      ]
images:
  - gcr.io/crypto-gohan/farmhand
timeout: 3600s
