steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/crypto-gohan/farmhand", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/crypto-gohan/farmhand"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "farmhand",
        "--image",
        "gcr.io/crypto-gohan/farmhand",
        "--region",
        "europe-west-1",
        "--platform",
        "managed",
      ]
images:
  - gcr.io/crypto-gohan/farmhand
timeout: 3600s
